import { formatInTimeZone } from "date-fns-tz";
import { createHash } from "node:crypto";

/**
 * Verifactu / SIF hash chain (Anexo I, Orden HAC/1177/2024; AEAT "Especificaciones
 * técnicas para la generación de la huella" v0.1.2).
 *
 * Each invoice's `current_hash` is SHA-256 of a `clave=valor` string joined by
 * `&`, returned as UPPERCASE hex (64 chars). The keys are mandatory — AEAT
 * rejects value-only concatenations with CodigoErrorRegistro 2000.
 *
 * Field order (RegistroAlta):
 *   IDEmisorFactura, NumSerieFactura, FechaExpedicionFactura, TipoFactura,
 *   CuotaTotal, ImporteTotal, Huella, FechaHoraHusoGenRegistro
 *
 * The first invoice of the chain sends `Huella=` (empty), not `0`.
 */
export type HashInput = {
  nif: string;
  invoiceNumber: string;
  invoiceType: string;
  issueDate: Date;
  taxAmount: number;
  total: number;
  previousHash: string | null;
  generatedAt: Date;
};

/**
 * Inputs used by the RegistroAnulacion hash. The cancelled invoice identity
 * identifies the record being annulled; the previous hash links this new
 * record to the last record generated by the SIF.
 */
export type CancellationHashInput = {
  nif: string;
  cancelledInvoiceNumber: string;
  cancelledInvoiceIssueDate: Date;
  previousHash: string | null;
  generatedAt: Date;
};

const MADRID_TZ = "Europe/Madrid";

function ddmmyyyy(d: Date): string {
  const dd = String(d.getUTCDate()).padStart(2, "0");
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const yyyy = String(d.getUTCFullYear());
  return `${dd}-${mm}-${yyyy}`;
}

function n2(x: number): string {
  return x.toFixed(2);
}

/**
 * Returns YYYY-MM-DDTHH:MM:SS+HH:MM (ISO 8601 / xs:dateTime) in Europe/Madrid
 * local time, as required by FechaHoraHusoGenRegistro (Anexo I, HAC/1177/2024).
 */
export function spanishTimestamp(d: Date): string {
  return formatInTimeZone(d, MADRID_TZ, "yyyy-MM-dd'T'HH:mm:ssxxx");
}

export function buildHashPayload(input: HashInput): string {
  const previous = input.previousHash?.trim() ?? "";
  return [
    `IDEmisorFactura=${input.nif.trim()}`,
    `NumSerieFactura=${input.invoiceNumber.trim()}`,
    `FechaExpedicionFactura=${ddmmyyyy(input.issueDate)}`,
    `TipoFactura=${input.invoiceType.trim()}`,
    `CuotaTotal=${n2(input.taxAmount)}`,
    `ImporteTotal=${n2(input.total)}`,
    `Huella=${previous}`,
    `FechaHoraHusoGenRegistro=${spanishTimestamp(input.generatedAt)}`,
  ].join("&");
}

export function computeInvoiceHash(input: HashInput): string {
  return createHash("sha256")
    .update(buildHashPayload(input), "utf8")
    .digest("hex")
    .toUpperCase();
}

/**
 * RegistroAnulacion hash payload (HAC/1177/2024, Anexo I): the three fields
 * identifying the annulled invoice, the preceding record hash, and generation
 * timestamp. The keys intentionally differ from RegistroAlta.
 */
export function buildCancellationHashPayload(
  input: CancellationHashInput,
): string {
  const previous = input.previousHash?.trim() ?? "";
  return [
    `IDEmisorFacturaAnulada=${input.nif.trim()}`,
    `NumSerieFacturaAnulada=${input.cancelledInvoiceNumber.trim()}`,
    `FechaExpedicionFacturaAnulada=${ddmmyyyy(input.cancelledInvoiceIssueDate)}`,
    `Huella=${previous}`,
    `FechaHoraHusoGenRegistro=${spanishTimestamp(input.generatedAt)}`,
  ].join("&");
}

export function computeCancellationHash(input: CancellationHashInput): string {
  return createHash("sha256")
    .update(buildCancellationHashPayload(input), "utf8")
    .digest("hex")
    .toUpperCase();
}
