name: Publish package

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: publish-verifactu
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-production
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: doscientos-es/actions/npm-auto-release@v1
        with:
          previous-sha: ${{ github.event.before }}
